# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tax_id',
            field=models.CharField(max_length=32, null=True, verbose_name='tax id'),
        ),
    ]
