# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170927_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundsTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funds_transfer_state', models.CharField(choices=[('PENDING', 'Pending order'), ('EXECUTED', 'Executed order'), ('CANCELLED', 'Cancelled order')], max_length=255, verbose_name='state')),
                ('amount_brl', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='BRL amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds_transfers', to='core.BillingAccount')),
            ],
            options={
                'verbose_name': 'Funds Transfer',
                'verbose_name_plural': 'Funds Transfers',
                'ordering': ('-created_at',),
            },
        ),
    ]
