language: python
python:
  - "3.6"
install:
  - cp contrib/env-sample .env
  - pip install -q -r requirements/prod.txt
script:
  - python manage.py check
  - python manage.py migrate
  - coverage run --source='trader' manage.py test
before_install:
  - pip install codecov
after_success:
  - codecov --token 8d1ab18e-7acf-4ecc-b8e1-1e7fd343af0d
